/* PAYLOAD SCAFFOLDING, generated by create-payload-app in a normal install.
   Written by hand here because npm could not run in the authoring environment.
   If `npx create-payload-app` ever emits a different version of this file for
   your exact Payload version, prefer theirs over this one. */
import type { ServerFunctionClient } from 'payload';
import config from '@payload-config';
import { RootLayout, handleServerFunctions } from '@payloadcms/next/layouts';
import React from 'react';

import { importMap } from './admin/importMap.js';

import '@payloadcms/next/css';

type Args = { children: React.ReactNode };

const serverFunction: ServerFunctionClient = async function (args) {
  'use server';
  return handleServerFunctions({ ...args, config, importMap });
};

/* This is a second root layout, parallel to (frontend)/layout.tsx. Route groups
   are transparent to the URL, so the admin renders inside Payload's own shell
   rather than inheriting the site's nav, footer and fonts. */
const Layout = ({ children }: Args) => (
  <RootLayout config={config} importMap={importMap} serverFunction={serverFunction}>
    {children}
  </RootLayout>
);

export default Layout;
