import { FINDINGS, type Finding } from '@/lib/playbooks/sources';

/**
 * The Data & AI Use Case Playbooks.
 *
 * Content as data rather than JSX, for two reasons. The page and the printable
 * one-pager render the same object, so the document a reader files cannot
 * disagree with the page they read it from — the same rule the calculator's
 * summary sheet follows. And a playbook that is data can be checked
 * mechanically: tools/check-playbooks.mjs walks these objects and fails if a
 * figure appears without a source attached to it.
 *
 * Written for the person who has been asked "what should we be doing with AI"
 * and has to come back with something defensible. That reader is not short of
 * lists of use cases; they are short of a way to tell which ones are real, what
 * each actually requires, and how they would know if it worked. So every use
 * case here carries what it needs and where it fails, and the failure modes are
 * not softened — a playbook that never says "don't" is a brochure.
 */

export type UseCase = {
  id: string;
  name: string;
  /** One line, for scanning. */
  summary: string;
  /** What it does, in terms an operations lead would use. */
  what: string;
  /** The data it needs before it can work at all. The usual reason projects stall. */
  needs: string[];
  /** How you would know it worked — stated before you start, not after. */
  proof: string;
  /** Where it goes wrong. Written plainly, because this is the useful part. */
  fails: string;
  /** Evidence backing the maturity claim, where any exists. */
  evidence?: Finding;
};

export type Playbook = {
  slug: string;
  industry: string;
  /**
   * The page's H1, and its title in a search result. Kept under 62 characters
   * so it is not truncated there.
   *
   * "Data and AI" rather than "AI", because two of the six use cases involve no
   * machine learning whatever and calling the set AI would be the same
   * overselling this document exists to argue against. It costs nothing in
   * search: "Data and AI Use Cases in Manufacturing" contains the phrase
   * people actually type, word for word.
   */
  title: string;
  /** Meta description and the listing card's blurb. */
  description: string;
  /** Who this is for, and who it is not for. */
  audience: string;
  /**
   * The opening paragraph, under the H1.
   *
   * Names the use cases outright rather than describing the document. Somebody
   * arriving on "AI use cases in manufacturing" wants to see the list in the
   * first sentence, and an assistant summarising the page quotes what is
   * nearest the heading.
   */
  standfirst: string;
  useCases: UseCase[];
  /** What has to be true before any of the above is worth starting. */
  readiness: { name: string; detail: string }[];
  /** Question-shaped, because these are the questions people actually type. */
  faq: { question: string; answer: string }[];
  /**
   * The industry motif from public/img, generated by tools/gen-art.mjs.
   *
   * Line art rather than a photograph, and the same grammar across all six: the
   * shape is the ordinary case, the accent mark is the exception the data is
   * for — a bottleneck on a line, a route running long, a spike in a trace. A
   * stock photograph of a factory would say only "factory".
   */
  image: string;
  published: boolean;
  updated: string;
};

const manufacturing: Playbook = {
  slug: 'manufacturing',
  industry: 'Manufacturing',
  title: 'Data and AI Use Cases in Manufacturing',
  description:
    'Six data and AI use cases in manufacturing, each with the data it requires, how to prove it worked, and where it fails. Every figure sourced, including the ones everyone quotes without checking.',
  audience:
    'Written for plant, operations and IT leads at manufacturers who have been asked what they should be doing with AI and need an answer they can defend. It assumes no data science background and no existing platform.',
  standfirst:
    'Six things manufacturers actually run on their data: predictive maintenance, automated visual inspection, demand forecasting, OEE analysis and scheduling, energy optimisation, and spares and inventory. Two of the six involve no machine learning at all. For each one this sets out the data it needs before it can work, how you would prove it worked, and the conditions under which it fails.',

  useCases: [
    {
      id: 'predictive-maintenance',
      name: 'Predictive maintenance',
      summary: 'Predict a failure from sensor data early enough to schedule the repair.',
      what:
        'Equipment sensor readings — vibration, temperature, current draw, acoustic signature — are monitored for the pattern that precedes a particular failure, so the machine is taken down deliberately rather than unexpectedly. The value is not fewer repairs; it is the same repairs, at a time you chose.',
      needs: [
        'Sensor data at an interval fine enough to see the failure develop. Hourly averages hide most bearing faults.',
        'A maintenance history that records what actually failed, not just that an engineer attended. This is the one that is usually missing.',
        'Enough past failures of the same kind to learn from. A machine that has failed twice in five years cannot support a model, whatever a vendor says.',
        'Somebody whose job it is to act on an alert. An unactioned prediction is a cost, not a saving.',
      ],
      proof:
        'Agree before you start: which asset, which failure mode, and what the current rate of unplanned stoppages on it is. Then measure the same number six months later. If nobody can state the current rate, that is the first project, not this one.',
      fails:
        'Most often for want of labelled failures, not for want of a model. It also fails quietly when the model is scored on accuracy. Worked example: suppose a machine fails on two days in a hundred — a model that always predicts "fine" is then right ninety-eight times out of a hundred, and is completely useless. Insist on being shown how often it caught real failures and how often it cried wolf, as two separate numbers.',
      evidence: FINDINGS.deploymentGap,
    },
    {
      id: 'visual-inspection',
      name: 'Automated visual inspection',
      summary: 'A camera and a model catch surface defects at line speed.',
      what:
        'Images of parts are classified as acceptable or not, on the line, at production rate. It suits defects that are genuinely visible and consistently defined: surface finish, print and label errors, missing components, weld appearance.',
      needs: [
        'Consistent lighting and camera position. This is more of the work than the model is, and skimping on it is the usual reason a pilot that worked stops working.',
        'Labelled example images of each defect type, including borderline ones.',
        'An agreed definition of a defect. Where two inspectors disagree, a model will disagree too, and you will blame the model.',
        'A decision about what happens to a rejected part, before go-live.',
      ],
      proof:
        'Run it alongside your existing inspection for a period, on the same parts, and compare. Count both the defects it missed and the good parts it rejected — the second is what quietly costs you money after go-live.',
      fails:
        'When the defect is not reliably visible in the image, when the product changes more often than the model is retrained, and when the true defect rate is so low that the training set contains almost no examples of what you are looking for.',
    },
    {
      id: 'demand-forecasting',
      name: 'Demand forecasting',
      summary: 'Forecast what will be ordered, to plan production and stock against it.',
      what:
        'Historical orders, seasonality and known external drivers are used to project demand by SKU and period. The output is only useful if it changes a decision — how much to make, what to hold, when to buy.',
      needs: [
        'Several years of order history at the granularity you plan at.',
        'A record of stock-outs. Sales history alone systematically understates demand you could not meet.',
        'Knowledge of promotions and one-off events, or the model will learn them as seasonality.',
      ],
      proof:
        'Compare against what you do now, which is usually last period plus a judgement. Measure forecast error on the same SKUs over the same window. A model that cannot beat "same as last month" is not ready, and finding that out early is a good outcome.',
      fails:
        'On short histories, on products with few large customers where one phone call outweighs any pattern, and after a genuine change in the market — a model trained on the past is confidently wrong about a step change.',
    },
    {
      id: 'oee-scheduling',
      name: 'OEE analysis and scheduling',
      summary: 'Find where output is actually lost, then schedule around it.',
      what:
        'Machine states, changeovers and stoppage reasons are combined into a picture of where availability, performance and quality are lost. Frequently the most valuable finding is that the losses are not where everyone assumed.',
      needs: [
        'Machine state capture that does not rely on someone filling in a sheet.',
        'A stoppage reason code list short enough to be used honestly. Forty codes become "other".',
        'Changeover times as they are, not as the standard says.',
      ],
      proof:
        'This one earns its place before any model does: if the loss analysis surprises the people who run the line, it has already paid for itself, and if it confirms what they knew, you have saved yourself the next project.',
      fails:
        'When the data is entered by the people being measured by it, without that conflict being acknowledged and designed around.',
    },
    {
      id: 'energy',
      name: 'Energy and utilities optimisation',
      summary: 'Match consumption to production, and find what draws power for nothing.',
      what:
        'Meter data is set against production output to find plant drawing power out of proportion to what it makes — compressed air leaks, chillers running against ambient conditions, equipment idling through breaks.',
      needs: [
        'Sub-metering. A single site meter tells you the total and nothing else.',
        'Production output on the same clock as the meter readings.',
        'Tariff structure, including any demand or peak charges, which often dominate the bill.',
      ],
      proof:
        'kWh per unit produced, before and after, on comparable production. Normalise for output or you will report a saving that is just a quiet month.',
      fails:
        'Rarely on the analysis and often on the follow-through: the finding is a maintenance job nobody is assigned, and twelve months later the leak is still there.',
    },
    {
      id: 'spares',
      name: 'Spares and inventory optimisation',
      summary: 'Hold the parts that would stop the line, and stop holding the rest.',
      what:
        'Consumption history, lead times and the consequence of a stock-out are used to set holdings per part. Cash is usually released rather than spent.',
      needs: [
        'Accurate lead times, which are frequently recorded as the supplier’s quote rather than reality.',
        'A criticality judgement per part — what actually stops if this is missing.',
        'Issue history from stores, at part level.',
      ],
      proof:
        'Value held against stock-outs causing downtime. Both, always: cutting inventory while causing one line stoppage is not a saving, and reporting only the first is how these projects get a bad name.',
      fails:
        'When criticality is inferred from price. The part that stops the plant is often cheap, and the expensive one on the shelf is often the one that never fails.',
    },
  ],

  readiness: [
    {
      name: 'You can say what a number means, and get the same answer twice',
      detail:
        'If two departments produce different output figures for the same week, that is the project. Every use case above inherits the definitions underneath it, and no model repairs a disagreement about what "produced" means.',
    },
    {
      name: 'The data leaves the machine that made it',
      detail:
        'Readings trapped in a PLC, an HMI or a local historian nobody can query are not available to anything. Getting them out reliably is unglamorous and is usually the longest task in the plan.',
    },
    {
      name: 'History exists, and goes back far enough',
      detail:
        'Models learn from what has happened. Six weeks of data supports nothing seasonal and no rare event, and no technique compensates for history that was never kept.',
    },
    {
      name: 'Somebody owns the decision the output feeds',
      detail:
        'Every use case above ends in a decision — take the machine down, reject the part, order the stock. Where no named person makes that decision today, the output has nowhere to go, and this is the most common reason a technically successful pilot is quietly abandoned.',
    },
  ],

  faq: [
    {
      question: 'How much does unplanned downtime actually cost a manufacturer?',
      answer:
        'The most quoted figure is about $1.4 trillion a year across the world’s 500 largest companies, roughly 11% of revenue, from Senseye and Siemens. It is worth knowing how that was arrived at before quoting it: 181 online interviews gathered over four years, combined with the publisher’s own product data, and the Global 500 total is extrapolated from public information rather than surveyed. The report itself calls its combined figures indicative only. It is a reasonable order of magnitude and a poor substitute for your own number, which you can get from your stoppage log and your contribution per hour.',
    },
    {
      question: 'Does AI predictive maintenance actually work, or is it a pilot that never ships?',
      answer:
        'Both, depending on the case. A 2025 review in Applied Sciences classified 60 published studies by how far they got: 40 reached live deployment with alerts feeding real work orders, 4 were validated retrospectively against plant data, and 16 never left benchmarks or simulation. So it demonstrably ships — and a third of the published work has not been tested against a real plant. Ask any vendor which of those three their evidence is.',
    },
    {
      question: 'What is the most common reason these projects fail?',
      answer:
        'Not the model. The recurring barrier in the published work is data: labelled failure examples are expensive and slow to gather, and industrial data is heterogeneous and heavily imbalanced. In practice the projects that stall are the ones where the maintenance history records that somebody attended, but not what failed.',
    },
    {
      question: 'Why should I distrust a high accuracy score on a failure-prediction model?',
      answer:
        'Because on a machine that fails on 2% of days, always predicting "no failure" is 98% accurate. Reviews of this literature note that high accuracy is frequently reported without disclosing how many faulty examples were in the data. Ask instead how many real failures it caught and how many false alarms it raised, as two separate numbers.',
    },
    {
      question: 'Where should a manufacturer start if none of this exists yet?',
      answer:
        'With the loss analysis, not with a model. Work out where output is actually lost and whether everyone agrees on the numbers. It is cheap, it needs no machine learning, and it tells you which of the use cases above is worth anything to you — which is a different answer at every plant.',
    },
  ],

  image: '/img/ind-manufacturing.svg',
  published: true,
  updated: '2026-08-30',
};


const oilAndGas: Playbook = {
  slug: 'oil-and-gas',
  industry: 'Oil & Gas',
  title: 'Data and AI Use Cases in Oil & Gas',
  description:
    'Six data and AI use cases in oil and gas, each with the data it needs, how to prove it worked, and where it fails. Sourced, including a published account of what a real offshore programme actually took.',
  audience:
    'Written for operations, integrity and digital leads at operators and service companies who need to separate what is running in production from what is running in a conference slide. It assumes no data science background.',
  standfirst:
    'Six things operators actually run on their data: rotating equipment monitoring, corrosion and integrity, production optimisation, flaring and emissions, drilling and completion analysis, and inventory for critical spares. For each one this sets out the data it needs, how you would prove it worked, and where it fails.',

  useCases: [
    {
      id: 'rotating-equipment',
      name: 'Rotating equipment monitoring',
      summary: 'Catch a turbine, compressor or pump degrading before it trips.',
      what:
        'Vibration, temperature, pressure and flow are watched for the signature that precedes a failure on a specific machine. On a platform the value is not the repair cost — it is avoiding an unplanned shutdown of production, and avoiding a helicopter mobilisation to fix something that could have been done on the next scheduled visit.',
      needs: [
        'A historian that actually holds the tags at the resolution the fault needs, and that somebody can query without raising a ticket.',
        'CMMS work orders that record what was found and what was replaced. The published offshore programme below hit exactly this: not all maintenance had gone through the work-order system.',
        'Somebody onshore who owns the alert and can get it into the next offshore work pack.',
        'Equipment engineers involved from the start. A modelling partner without domain knowledge slows the work rather than speeding it.',
      ],
      proof:
        'Pick the assets and the failure modes first, and write down the current rate of unplanned trips on them. Six months later, count again. Also count alerts that led to an intervention against alerts that were dismissed — a model nobody acts on is a subscription, not a system.',
      fails:
        'It stalls on data availability far more often than on modelling, and the delay is measured in months not weeks. It also fails when the alert says only that something is abnormal: a "check engine" light on a compressor tells an offshore team nothing they can act on, and they stop opening them.',
      evidence: FINDINGS.offshoreDataFirst,
    },
    {
      id: 'corrosion-integrity',
      name: 'Corrosion and asset integrity',
      summary: 'Target inspection at the parts of the system most likely to be thinning.',
      what:
        'Inspection history, process conditions, fluid composition and material data are combined to rank circuits by likely degradation, so inspection effort goes where the risk is rather than where the schedule says.',
      needs: [
        'Inspection results in a queryable form, not as scanned PDFs of reports.',
        'Consistent circuit and location identifiers across the systems. This is usually the hard part: the same line has three identifiers in three systems.',
        'Process history for the same period as the inspection findings.',
      ],
      proof:
        'Compare the ranking against what the next inspection campaign actually finds. It is a good sign when the model puts thinning at the top of the list before anyone has looked, and an honest failure when it does not.',
      fails:
        'Where inspection coverage has been driven by accessibility rather than risk, the history is biased towards what was easy to reach — and a model trained on it inherits that blind spot precisely where you most need it not to.',
    },
    {
      id: 'production-optimisation',
      name: 'Production optimisation',
      summary: 'Find where wells and facilities are running below what conditions allow.',
      what:
        'Well tests, choke settings, pressures and facility constraints are used to find the gap between what a well is producing and what it could produce, and to say which constraint is binding.',
      needs: [
        'Well test data at a usable frequency, and honesty about how old each test is.',
        'Facility constraints written down somewhere other than in an operator’s head.',
        'Allocation that reconciles, or the model will optimise against a number that is already wrong.',
      ],
      proof:
        'Against the current process, on the same wells, over a period long enough to cover normal variation. Uplift claimed against a best-ever month is not uplift.',
      fails:
        'When allocation is contested. If two departments disagree about what a well produced last month, no optimisation of that figure will be believed, and the argument is the project.',
    },
    {
      id: 'flaring-emissions',
      name: 'Flaring and emissions monitoring',
      summary: 'Account for what is flared and vented, and find the recurring causes.',
      what:
        'Flare meter data, process events and equipment status are brought together to attribute flaring to causes — a compressor trip, a start-up, a specific plant upset — rather than reporting a monthly total nobody can act on.',
      needs: [
        'Flare metering that is calibrated, and known gaps where it is not.',
        'Event and alarm history on the same clock as the flare data.',
        'An agreed reporting basis, because the regulatory figure and the engineering figure are rarely the same number.',
      ],
      proof:
        'Volume attributed to an identified cause, as a share of the total. Going from "we flared this much" to "this much of it came from these four causes" is the whole value, and it is measurable.',
      fails:
        'When metering is poor and the analysis quietly becomes an estimate presented with the confidence of a measurement — which is a problem if the number ends up in a regulatory return.',
    },
    {
      id: 'drilling-analysis',
      name: 'Drilling and completion analysis',
      summary: 'Compare wells honestly enough to learn something from the last one.',
      what:
        'Daily reports, mud logs, bit records and time breakdowns are normalised so that wells can be compared — where non-productive time went, which parameter choices went with better runs.',
      needs: [
        'Daily drilling reports in a structured form. They are usually free text, and turning them into data is most of the work.',
        'A consistent operations coding scheme across rigs and contractors.',
        'Enough wells in comparable formations to draw any conclusion at all.',
      ],
      proof:
        'Non-productive time per well section against the historical baseline for the same formation. Comparing against a different field is not a comparison.',
      fails:
        'On small samples. A dozen wells across three basins supports anecdote, not inference, and dressing that up as a model gives the anecdote unearned authority.',
    },
    {
      id: 'critical-spares',
      name: 'Critical spares and inventory',
      summary: 'Hold what a shutdown would turn on, and stop holding the rest.',
      what:
        'Consumption, lead time and the cost of a stock-out set holdings for each part. In this sector the asymmetry is severe: an inexpensive seal can hold up production worth far more than the whole store.',
      needs: [
        'Real lead times, which for long-lead items are frequently recorded as the original quote rather than as delivered.',
        'A criticality judgement per part, made by engineers rather than inferred from price.',
        'Issue history at part level, including what was cannibalised from another unit.',
      ],
      proof:
        'Value held against stock-outs that caused deferment. Report both or the exercise becomes a cost-cutting number with a production loss hidden behind it.',
      fails:
        'When criticality is inferred from cost. The part that stops the platform is often cheap, and the expensive one on the shelf is often the one that never fails.',
    },
  ],

  readiness: [
    {
      name: 'The historian is reachable, and the tags mean what they say',
      detail:
        'Every use case here starts with time-series data somebody can query. Where the tag list is undocumented and half the names are inherited from a previous operator, that is the first piece of work and it is not a modelling task.',
    },
    {
      name: 'Maintenance history records what failed, not just that somebody attended',
      detail:
        'This is the single most common gap, and it is documented in the offshore programme cited above: maintenance that never went through the work-order system leaves no history to learn from. It cannot be reconstructed later.',
    },
    {
      name: 'One identifier per physical thing, across systems',
      detail:
        'A line, a vessel or a pump usually carries different identifiers in the historian, the CMMS and the inspection database. Until they can be joined, every one of these use cases is a manual reconciliation exercise wearing a model.',
    },
    {
      name: 'An onshore owner for every alert',
      detail:
        'Offshore crews are busy and an alert without a named owner onshore is an alert that gets acknowledged and forgotten. This is a rota question, not a technology one, and it decides whether any of this survives its first six months.',
    },
  ],

  faq: [
    {
      question: 'How long does an offshore predictive maintenance programme take to produce anything?',
      answer:
        'Longer than the pilot timeline usually says. In a published account of a 24-month programme across deepwater Gulf of Mexico platforms, the first predictive model went live six months after kickoff, and the operator attributed the delay to a lack of the required data rather than to modelling difficulty. Forty-six models were eventually running in production. Plan for the data work to be the schedule.',
    },
    {
      question: 'What is the most common data problem in oil and gas AI projects?',
      answer:
        'Maintenance history that records an intervention but not a failure mode. The offshore programme cited here found that not all maintenance had been raised through the work-order system, so the record of what actually failed was incomplete. Sensor data is usually abundant; the labels that make it useful are usually not.',
    },
    {
      question: 'Why do offshore crews stop acting on model alerts?',
      answer:
        'Because early alerts tend to behave like a check-engine light — they say something is abnormal without saying what or what to do. The published programme describes exactly this and had to retrain models to reduce false positives. An alert that cannot be turned into a work-pack line is an alert that gets dismissed, and once dismissal becomes habit the system is finished regardless of its accuracy.',
    },
    {
      question: 'Do we need a data scientist or an equipment engineer?',
      answer:
        'Both, and the second is the one usually missing. The offshore programme reported that its service partner lacked sufficient expertise in oil and gas equipment, which hampered the work. A model that does not know a glycol system from a gas compressor produces alerts that a rotating equipment engineer can see are nonsense.',
    },
    {
      question: 'Where should an operator start if none of this exists yet?',
      answer:
        'With whether the historian and the CMMS can be joined on a common identifier for the same physical asset. It needs no machine learning, it is the prerequisite for every use case above, and finding out that it cannot be done is worth knowing before a modelling contract is signed rather than after.',
    },
  ],

  image: '/img/ind-energy.svg',
  published: true,
  updated: '2026-08-30',
};


const logistics: Playbook = {
  slug: 'logistics',
  industry: 'Logistics',
  title: 'Data and AI Use Cases in Logistics',
  description:
    'Six data and AI use cases in logistics and distribution, each with the data it needs, how to prove it worked, and where it fails. Every figure sourced, with what the published forecasting evidence does and does not support.',
  audience:
    'Written for operations, network and IT leads at carriers, 3PLs and distributors who need to know which of these is worth starting and what each one will demand of their data first. It assumes no data science background.',
  standfirst:
    'Six things logistics operations actually run on their data: demand and volume forecasting, route and load planning, warehouse slotting, ETA prediction, fleet maintenance, and freight cost and invoice audit. Two of the six need no machine learning. For each one this sets out the data it needs, how you would prove it worked, and where it fails.',

  useCases: [
    {
      id: 'volume-forecasting',
      name: 'Demand and volume forecasting',
      summary: 'Forecast what will need moving, to staff and book capacity against it.',
      what:
        'Order and shipment history, seasonality and known drivers project volume by lane, site and period. The output only matters if it changes something you commit to in advance — shifts rostered, vehicles booked, space taken.',
      needs: [
        'Several years of history at the granularity you actually plan at. A network total does not help a site manager staff a shift.',
        'A record of what you turned away or could not move, or the history understates demand exactly where it was tightest.',
        'Promotions, contract wins and losses marked, or the model learns a one-off customer as a season.',
      ],
      proof:
        'Against your current method, which is usually last period plus judgement, on the same lanes over the same window. The published reviews report machine learning beating classical baselines by meaningful margins, but those are the authors’ datasets and not a promise about yours — your own baseline is the only comparison that decides anything.',
      fails:
        'On lanes dominated by a handful of customers, where one contract decision outweighs any pattern in the history. It also fails after a genuine step change in the network, because a model trained on the old shape is confident and wrong.',
      evidence: FINDINGS.forecastGains,
    },
    {
      id: 'route-load-planning',
      name: 'Route and load planning',
      summary: 'Build drops and loads that respect what the vehicle and the driver can actually do.',
      what:
        'Orders, vehicle capacities, time windows and driver hours are solved into routes. This is optimisation rather than learning, and it is one of the two here that involves no machine learning at all.',
      needs: [
        'Accurate service times per drop. Planned times that everyone knows are wrong produce routes nobody runs.',
        'Real vehicle constraints, including the ones drivers work around informally.',
        'Access restrictions and delivery windows as they are enforced, not as the customer master says.',
      ],
      proof:
        'Planned versus actual, per route, over a month: how many drops moved, how much time was added, how often a driver rebuilt the run themselves. A plan the depot quietly overrides has failed however good the objective function looks.',
      fails:
        'When the model’s picture of a drop is a customer record and the driver’s is a loading bay with a locked gate at four o’clock. The gap between those two is where these projects die.',
    },
    {
      id: 'warehouse-slotting',
      name: 'Warehouse slotting',
      summary: 'Put fast-moving stock where it costs least to pick.',
      what:
        'Pick history, product dimensions and affinity between items decide where each SKU sits, cutting travel per pick. Also not machine learning — it is counting and arithmetic, and it usually pays back faster than anything else on this list.',
      needs: [
        'Pick-level history with location and timestamp, not order-level summaries.',
        'Accurate product dimensions and weights, which are very often wrong in the master data.',
        'A window in which to physically move stock, which is an operational cost people forget to budget.',
      ],
      proof:
        'Travel distance or picks per hour, measured before and after on comparable volume. Normalise for volume or a quiet month will look like an improvement.',
      fails:
        'When the analysis is run once and never again. Slotting decays as the range changes, and a layout optimised for last spring is worse than one nobody optimised.',
    },
    {
      id: 'eta-prediction',
      name: 'ETA prediction',
      summary: 'Tell a customer when it will arrive, and be right often enough to be believed.',
      what:
        'Telematics, historical transit times, traffic and dwell patterns predict arrival windows for a consignment in flight.',
      needs: [
        'Position data at a frequency that captures dwell, not just departure and arrival.',
        'Historical actuals per lane, including the bad days rather than a cleaned set.',
        'A defined event for "arrived", because gate-in, unload and POD are three different times and pretending otherwise makes the whole measurement incoherent.',
      ],
      proof:
        'The share of deliveries landing inside the promised window, and the size of the misses when they fall outside. Publishing a narrow window you hit half the time is worse than a wide window you hit reliably.',
      fails:
        'At the last leg and in yards, where the variance actually lives. A model that nails line-haul and cannot predict a three-hour wait for a door is a model that gets the customer promise wrong.',
    },
    {
      id: 'fleet-maintenance',
      name: 'Fleet maintenance',
      summary: 'Take the vehicle off the road on your schedule, not on the hard shoulder.',
      what:
        'Telematics fault codes, service history and duty cycle are used to schedule work before a breakdown. The value is a planned VOR instead of a recovery and a failed delivery.',
      needs: [
        'Fault codes retained rather than cleared at service, which many workshops do by default.',
        'Service history joined to the vehicle across its whole life, including under a previous operator.',
        'Duty cycle, since the same vehicle on urban multi-drop and on trunking degrades differently.',
      ],
      proof:
        'Roadside breakdowns per vehicle per year, against the same period before. Count planned VOR hours too — trading a breakdown for excessive precautionary downtime is not a win.',
      fails:
        'On mixed fleets with too few of any one model to learn from, and where the maintenance record lives with a contracted workshop who has no reason to give you the detail.',
    },
    {
      id: 'freight-audit',
      name: 'Freight cost and invoice audit',
      summary: 'Check what you were charged against what was agreed and what moved.',
      what:
        'Carrier invoices are reconciled against rate cards, actual weights and dimensions, and the shipment record. Overcharges are usually not fraud — they are re-weighs, accessorials and surcharges that nobody has capacity to check line by line.',
      needs: [
        'Rate cards in a structured form. They frequently arrive as PDFs and turning them into data is the project.',
        'Dimensional data captured at despatch, or you cannot dispute a re-weigh.',
        'A shipment record that can be matched to an invoice line, which sounds trivial and rarely is.',
      ],
      proof:
        'Recovered or avoided spend as a share of freight cost, and the share of invoice lines checked. The second matters: auditing a small sample and extrapolating from it is an estimate, not a finding.',
      fails:
        'When the dispute process costs more than the recovery. Finding an error you will never claim back is an expensive way to feel informed.',
    },
  ],

  readiness: [
    {
      name: 'One identifier follows a consignment end to end',
      detail:
        'Order, shipment, consignment and invoice usually carry different references in different systems. Until they join, every use case here starts with a reconciliation exercise, and most of the effort goes there rather than into the analysis.',
    },
    {
      name: 'Events are timestamped consistently, and "arrived" is defined',
      detail:
        'Gate-in, unload start and POD are three different moments. Where sites record them differently, transit and dwell figures are not comparable between them, and any model built on the mixture inherits the inconsistency.',
    },
    {
      name: 'Master data reflects reality, not the contract',
      detail:
        'Service times, dimensions, access restrictions and delivery windows are frequently what was agreed years ago rather than what happens now. Planning against them produces plans the depot overrides, which is the most common way these projects quietly stop being used.',
    },
    {
      name: 'Somebody owns the decision each output feeds',
      detail:
        'A forecast changes a staffing commitment; a route plan changes what a driver is handed; an audit finding changes a claim. Where no named person makes that call today, the output has nowhere to go, and a technically successful pilot gets abandoned anyway.',
    },
  ],

  faq: [
    {
      question: 'Does machine learning actually forecast logistics demand better than traditional methods?',
      answer:
        'The published evidence says yes, with caveats worth knowing. A 2024 critical review of 119 studies found machine-learning forecasters reporting error reductions of roughly 15–20% against ARIMA, with hybrid models reporting further gains. Those figures are what each set of authors measured on their own data, not a promise about your lanes, and the same review names unreliable input data — missing history, or bias in what was recorded — as a limit that no choice of model removes. Your own current method is the only baseline that decides anything.',
    },
    {
      question: 'Which logistics use case pays back fastest?',
      answer:
        'Usually warehouse slotting or freight invoice audit, and neither involves machine learning. Slotting is counting pick history and moving stock; audit is reconciling invoices against rate cards. Both are unglamorous, both are measurable within a quarter, and both are frequently skipped in favour of something with a better name.',
    },
    {
      question: 'Why do route optimisation projects get rejected by depots?',
      answer:
        'Because the model plans against master data and the driver runs against reality — service times that are optimistic, a delivery window the customer enforces differently, a gate locked at four. When the plan and the ground disagree, the depot rebuilds the run by hand and the system becomes something to work around. The fix is fixing the master data, which is slower and less interesting than the optimisation.',
    },
    {
      question: 'What data do we need before ETA prediction is worth attempting?',
      answer:
        'Position data frequent enough to show dwell rather than just departure and arrival, historical actuals per lane including the bad days, and an agreed definition of "arrived". That last one decides everything downstream: gate-in, unload and POD are three different times, and a model trained on a mixture of them cannot be accurate about any of them.',
    },
    {
      question: 'Where should a logistics operation start if none of this exists yet?',
      answer:
        'By checking whether a consignment can be traced end to end on one identifier, and whether every site means the same thing by "arrived". Neither needs machine learning, both are prerequisites for most of the list above, and discovering that they do not hold is worth more than a forecasting pilot built on top of the gap.',
    },
  ],

  image: '/img/ind-logistics.svg',
  published: true,
  updated: '2026-08-30',
};


const fintech: Playbook = {
  slug: 'fintech',
  industry: 'Fintech',
  title: 'Data and AI Use Cases in Fintech',
  description:
    'Six data and AI use cases in fintech and lending, each with the data it needs, how to prove it worked, and where it fails — including why accuracy is the wrong measure for anything this rare.',
  audience:
    'Written for risk, operations and technology leads at lenders, payment companies and financial platforms who need to know what these models require and what they will be asked to defend. It assumes no data science background.',
  standfirst:
    'Six things financial firms actually run on their data: transaction fraud detection, credit decisioning, anti-money-laundering triage, collections prioritisation, churn, and reconciliation. Every one has a regulator or an auditor attached, which changes what "working" means. For each this sets out the data it needs, how you would prove it worked, and where it fails.',

  useCases: [
    {
      id: 'fraud-detection',
      name: 'Transaction fraud detection',
      summary: 'Score a transaction in flight, and decide whether to let it through.',
      what:
        'Transaction attributes, device and behavioural signals and the customer’s own history produce a score inside the time available before authorisation. The decision is never only the model’s: a threshold turns a score into an action, and where that threshold sits is a business judgement about the relative cost of a missed fraud and a blocked customer.',
      needs: [
        'Confirmed fraud outcomes joined back to the original transaction. Chargebacks arrive months later, which means today’s labels describe last quarter’s fraud.',
        'Features you can actually compute inside the latency budget. A signal that takes 400ms is not available at authorisation.',
        'A record of what you blocked. Without it the training data contains only fraud that got through, so the model learns from the fraud you were already worst at catching.',
        'A named owner for the threshold, and a process for moving it.',
      ],
      proof:
        'Never accuracy. Precision and recall separately, precision-recall AUC, and the two costs stated in money: fraud missed, and good customers declined. A model that improves one while quietly worsening the other has not improved anything.',
      fails:
        'On the feedback loop. Blocked transactions never produce an outcome, so the model stops learning about the fraud it already catches and drifts toward what it misses. It also fails quietly when a pattern changes: performance degrades for weeks before anyone notices, unless somebody watches the score distribution rather than the headline metric.',
      evidence: FINDINGS.fraudBaseRate,
    },
    {
      id: 'credit-decisioning',
      name: 'Credit decisioning',
      summary: 'Estimate the probability that this borrower will not repay.',
      what:
        'Application data, bureau data and, where permitted, transaction history estimate default risk. The model is one input to a decision that must be explainable to the applicant and defensible to a regulator, which rules out techniques that would otherwise score better.',
      needs: [
        'Outcomes observed over a full credit cycle. A model trained only on a benign period has never seen the conditions it exists to price.',
        'Rejected applications, and some way of reasoning about them. You observe repayment only for people you accepted.',
        'A feature set you can defend one attribute at a time as not being a proxy for something you must not price on.',
        'Reason codes. An applicant is entitled to know why, and "the model said so" is not an answer.',
      ],
      proof:
        'Against the existing scorecard, on the same applicants, over a window long enough for outcomes to mature. Approval rate and loss rate together — improving either alone is trivial and means nothing.',
      fails:
        'On reject inference and on proxies. A postcode is not an ethnicity field and can behave like one; a model that has never seen the people you declined cannot say what declining them cost. Both are invisible in a validation score and obvious in a regulatory review.',
    },
    {
      id: 'aml-triage',
      name: 'AML alert triage',
      summary: 'Rank the alert queue so investigators start where the risk is.',
      what:
        'Existing rule-based alerts are scored for likely materiality so a team can work the queue in a sensible order. Note what this is not: it does not replace the rules, and in most jurisdictions it cannot decide that something goes unreviewed.',
      needs: [
        'Investigation outcomes recorded consistently — what was escalated, what was closed, and why. Free-text closure notes are the usual blocker.',
        'The full alert history including everything closed as a false positive, which is where most of the signal is.',
        'Compliance in the room from the start, because the binding constraint is regulatory before it is technical.',
      ],
      proof:
        'Time to first escalation, and the share of escalations found in the top decile of the ranking. Not "alerts reduced" — that is not the objective and it reads badly in an inspection.',
      fails:
        'When triage quietly becomes suppression. Ranking an alert lower is defensible; a model that closes one usually is not, and the difference matters enormously to a regulator even when the mathematics is identical.',
    },
    {
      id: 'collections',
      name: 'Collections prioritisation',
      summary: 'Work the accounts where contact will change the outcome.',
      what:
        'Arrears history, payment behaviour and contact history estimate which accounts will self-cure and which need intervention, so limited collections capacity goes where it changes something.',
      needs: [
        'Contact history with outcomes, not merely attempts.',
        'A clean definition of cure, and consistency about when the clock starts.',
        'Visibility of which customers are in hardship, because prioritising on recoverability alone produces conduct problems.',
      ],
      proof:
        'Roll rates and cure rates against the current strategy on comparable arrears buckets, plus amount recovered per collector hour.',
      fails:
        'When it optimises purely for recovery. A model that learns to chase hardest the people least able to pay is doing exactly what it was asked and creating a conduct issue, and no validation metric will flag it.',
    },
    {
      id: 'churn',
      name: 'Customer churn and retention',
      summary: 'Spot the accounts about to leave, early enough to act.',
      what:
        'Balance, transaction frequency, product holdings and service contacts predict attrition, so retention effort is spent before the decision is made rather than after it.',
      needs: [
        'A definition of churn that fits the product. A dormant current account and a closed one are different things.',
        'Enough lead time for the prediction to be actionable. Knowing on the day of closure is knowing nothing.',
        'Service history, which is frequently in a separate system nobody has joined to the account.',
      ],
      proof:
        'A holdout that receives no intervention. Without one, every customer who stays looks like a save, including everybody who was never leaving.',
      fails:
        'When the retention offer goes to whoever scores highest, including customers who would have stayed anyway. That is not retention spend, it is a discount programme with a model attached.',
    },
    {
      id: 'reconciliation',
      name: 'Reconciliation and exception handling',
      summary: 'Match what cleared against what you recorded, and surface only the breaks.',
      what:
        'Ledger entries, settlement files and bank statements are matched, leaving a much smaller exceptions queue. Mostly matching logic rather than machine learning, and usually the fastest payback on this list.',
      needs: [
        'Consistent references across systems, or a documented rule for deriving them.',
        'Timing conventions written down: cut-offs, value dates, and what a weekend does.',
        'A route for an exception to be resolved rather than merely flagged.',
      ],
      proof:
        'Auto-match rate, exceptions per thousand transactions, and hours spent reconciling. All three: the first without the third can hide work that simply moved somewhere else.',
      fails:
        'When tolerances are loosened to raise the auto-match rate. The number improves and real breaks pass through, which is precisely the wrong trade in a control process.',
    },
  ],

  readiness: [
    {
      name: 'Outcomes are joined back to the decision that produced them',
      detail:
        'Fraud, default, cure, churn — each is observed long after the decision it judges. Where the two cannot be joined there are no labels, and none of the models above can be built or evaluated however much transaction data exists.',
    },
    {
      name: 'You keep a record of what you declined',
      detail:
        'Blocked transactions and rejected applications produce no outcome, so every model trained on what you accepted is trained on a sample you selected. It cannot be repaired retrospectively, and it is the most consequential data decision on this list.',
    },
    {
      name: 'Every feature can be defended one at a time',
      detail:
        'In a regulated decision the question is not only whether the model performs but whether each input is permissible and each outcome explainable. A feature set nobody can walk through attribute by attribute is a model that will not survive its first review.',
    },
    {
      name: 'Somebody owns the threshold, not just the model',
      detail:
        'A score does nothing until a threshold turns it into an action, and where that sits is a commercial and conduct judgement rather than a technical one. Projects that never name the owner of that number end up with it set by whoever built the model.',
    },
  ],

  faq: [
    {
      question: 'Why is accuracy the wrong way to measure a fraud model?',
      answer:
        'Because fraud is rare. In the public credit-card dataset used across this literature, 0.172% of transactions are fraudulent — about one in 577 — so a model that labels everything legitimate is over 99.8% accurate and catches nothing. The published work uses precision, recall, F1 and precision-recall AUC instead, the last specifically because it describes minority-class performance where ROC-AUC flatters it. If a vendor quotes an accuracy figure for a fraud model, that is the review finished.',
    },
    {
      question: 'What data problem stops credit models being usable?',
      answer:
        'Reject inference. You observe repayment only for applicants you accepted, so a model trained on the accepted book has never seen the people you declined and cannot tell you whether declining them was right. It is not a modelling detail but a structural bias in the only data you have, and every honest answer to it is expensive.',
    },
    {
      question: 'Can a model close AML alerts?',
      answer:
        'Ranking an alert queue is defensible. Closing alerts usually is not, and that distinction matters far more to a regulator than the mathematics behind it. Treat triage as ordering the work rather than reducing it, and measure the share of true escalations found at the top of the ranking rather than the number of alerts avoided.',
    },
    {
      question: 'How do we know a retention model actually retained anyone?',
      answer:
        'By keeping a holdout that receives no intervention. Without one, every customer who stays looks like a save, including everybody who was never leaving, and the programme reports a return it did not earn. It is the most common measurement failure in retention work and entirely avoidable.',
    },
    {
      question: 'Where should a financial firm start if none of this exists yet?',
      answer:
        'With reconciliation. It is mostly matching logic rather than machine learning, it pays back in weeks, it forces exactly the data hygiene every other use case here depends on — consistent references, agreed timing conventions — and nobody will ask you to explain it to a regulator.',
    },
  ],

  image: '/img/ind-financial.svg',
  published: true,
  updated: '2026-08-30',
};


const retail: Playbook = {
  slug: 'retail-ecommerce',
  industry: 'Retail & E-commerce',
  title: 'Data and AI Use Cases in Retail & E-commerce',
  description:
    'Six data and AI use cases in retail and e-commerce, each with the data it needs, how to prove it worked, and where it fails — including published evidence that the fashionable model is not the one that wins.',
  audience:
    'Written for trading, supply chain and technology leads at retailers and e-commerce businesses who need to know which of these is worth starting and what each will demand of their data first. It assumes no data science background.',
  standfirst:
    'Six things retailers actually run on their data: demand forecasting, replenishment and allocation, markdown and pricing, personalisation and recommendation, returns and fraud, and availability analysis. For each this sets out the data it needs before it can work, how you would prove it worked, and the conditions under which it fails.',

  useCases: [
    {
      id: 'demand-forecasting',
      name: 'Demand forecasting',
      summary: 'Forecast what will sell, by product and location, far enough ahead to act.',
      what:
        'Sales history, seasonality, price, promotions and calendar effects project demand per SKU and store. It matters only where it changes a commitment — what you buy, what you make, what you move, how you staff.',
      needs: [
        'History at the grain you plan at. A chain total does not help a store manager order.',
        'Out-of-stock periods marked, or the model learns your shortages as low demand and reorders the shortage.',
        'Promotions and price changes as a dated record, not reconstructed from memory.',
        'Calendar effects that matter locally — festivals, school terms, paydays — which in India move against the Gregorian calendar and wreck a model that assumes otherwise.',
      ],
      proof:
        'Against your current method on the same SKUs and stores over the same window, using an error measure agreed before you start. Published comparisons favour tree-based ensembles over deep learning on real supermarket data, so start with the simpler thing and make the complicated one earn its place.',
      fails:
        'On short life-cycles and new products, where there is no history to learn from and the model is confidently extrapolating from something else. It also fails when it is scored on forecast error while the business is judged on availability, so the two never agree about whether it worked.',
      evidence: FINDINGS.retailTreesBeatDeepLearning,
    },
    {
      id: 'replenishment',
      name: 'Replenishment and allocation',
      summary: 'Send the right quantity to the right place before it sells out.',
      what:
        'Forecast, current stock, lead times and shelf capacity decide order quantities and how a delivery is split between stores. This is arithmetic on top of a forecast rather than a model in its own right, and it is where forecasting either pays or does not.',
      needs: [
        'Stock accuracy at store level. Where the book says three and the shelf has none, every downstream decision is wrong and no forecast fixes it.',
        'Real lead times including the variance, not the agreed service level.',
        'Shelf capacity and case sizes, or the system will order what will not fit.',
      ],
      proof:
        'Availability and stock cover together, plus waste for anything perishable. Availability alone is trivially improved by holding more of everything.',
      fails:
        'On inventory record accuracy, almost always. This is a counting and process problem rather than an analytical one, and it defeats more replenishment projects than every modelling issue combined.',
    },
    {
      id: 'pricing-markdown',
      name: 'Markdown and pricing',
      summary: 'Decide when to cut, and by how much, while it still sells.',
      what:
        'Sell-through rate, remaining stock, time left in the season and price elasticity where it can be estimated decide markdown depth and timing. The prize is not a lower markdown but a smaller residual.',
      needs: [
        'Clean price history, including what was actually charged after every promotion rather than the list price.',
        'Enough price variation to estimate elasticity. If a line has never moved in price, the data cannot tell you what would happen if it did.',
        'Season end dates and residual disposal costs, or the model has no deadline to optimise against.',
      ],
      proof:
        'Gross margin after markdown and residual units, against a comparable prior season. Reporting one without the other is how a markdown programme claims success while the stockroom fills.',
      fails:
        'When elasticity is estimated from promotional periods and applied to base pricing. The two behave differently, and a model that conflates them will recommend cuts that buy volume you already had.',
    },
    {
      id: 'personalisation',
      name: 'Personalisation and recommendation',
      summary: 'Show a customer something they would not have found on their own.',
      what:
        'Browse and purchase behaviour rank what to show. The commercial question is not whether it lifts click-through but whether it lifts basket value — recommending what somebody was going to buy anyway is easy and worth nothing.',
      needs: [
        'Behaviour joined to a persistent customer identifier across sessions and devices.',
        'A cold-start answer for new customers and new products, which is most of the catalogue in most retailers.',
        'A consent position that matches what you actually do with the data, because the privacy policy is part of the system.',
      ],
      proof:
        'A holdout that sees no recommendations, measured on incremental basket value rather than click-through. Attribution without a holdout will credit the recommender with sales it did not cause.',
      fails:
        'By collapsing onto the popular. A recommender optimised on click-through learns to show bestsellers, which raises the metric and adds nothing a category page would not have done.',
    },
    {
      id: 'returns-fraud',
      name: 'Returns and refund abuse',
      summary: 'Separate a genuine return from a pattern of abuse.',
      what:
        'Return rates by customer, product and reason code identify both the products that are failing customers and the small number of accounts systematically abusing the policy.',
      needs: [
        'Reason codes that staff actually use, which means few enough to be picked honestly under time pressure.',
        'Returns joined to the original order and the customer, including guest checkouts.',
        'Product-level return history, because a high rate is often a sizing or description problem rather than a customer problem.',
      ],
      proof:
        'Return rate by cohort against the change made, and abuse recovered. Watch the false-positive cost carefully: accusing a good customer of fraud is expensive in a way no dashboard shows.',
      fails:
        'When it is treated as a fraud problem first. Most excess returns are caused by inaccurate product information, and a model pointed at customers will never find that.',
    },
    {
      id: 'availability',
      name: 'Availability and phantom stock',
      summary: 'Find the lines the system thinks are in stock and the shelf does not.',
      what:
        'Sales patterns that stop abruptly while stock-on-hand stays positive identify likely phantom inventory — the book says you have it, the shelf disagrees. No machine learning required, and frequently the highest-value thing on this list.',
      needs: [
        'Sales at a daily grain per store and SKU.',
        'Stock-on-hand snapshots on the same clock as the sales.',
        'A process for someone to check a flagged line, which is the part that gets forgotten.',
      ],
      proof:
        'The share of flagged lines confirmed as wrong when somebody physically checks. If most flags are correct, this pays for itself immediately; if not, the rule needs tuning before anyone is sent to look.',
      fails:
        'When nobody is assigned to check. A phantom stock report that nobody walks the aisle for is a list of known problems, which is worse than not knowing because it removes the excuse.',
    },
  ],

  readiness: [
    {
      name: 'The stock number is true',
      detail:
        'Replenishment, allocation, availability and forecasting all inherit inventory accuracy. Where the book and the shelf disagree, every one of them is optimising against a fiction — and this is a counting and process problem, not an analytical one.',
    },
    {
      name: 'Out-of-stocks are recorded, not silently absent',
      detail:
        'Sales history with unmarked stock-outs understates demand exactly where demand was highest. A forecast trained on it reorders the shortage, and the error compounds every cycle it is not corrected.',
    },
    {
      name: 'One customer identifier survives across sessions and channels',
      detail:
        'Personalisation, returns analysis and lifetime value all need behaviour joined to a person rather than to a session. Where guest checkout and app and web produce three unlinked identities, none of them can be built honestly.',
    },
    {
      name: 'The local calendar is in the data',
      detail:
        'Festivals, school terms and paydays move demand more than most seasonality, and in India they move against the Gregorian calendar. A model that has only seen month numbers cannot learn them, and will be wrong in the same weeks every year.',
    },
  ],

  faq: [
    {
      question: 'Do we need deep learning for retail demand forecasting?',
      answer:
        'The published evidence says start simpler. A study using six years of daily demand from an Austrian supermarket — over 330 products and 5.2 million records across fruit, fresh meat and soft drinks — found tree-based ensembles outperforming LSTM deep learning on every metric reported, with the widest gap on fresh meat. That is one retailer in one country, so treat the direction rather than the margin as transferable. But it is a good reason to make the complicated model beat the simple one on your own data before buying it.',
    },
    {
      question: 'What is the most common reason retail forecasting projects disappoint?',
      answer:
        'Inventory accuracy, and unmarked stock-outs. If the book says three and the shelf has none, every replenishment decision downstream is wrong regardless of forecast quality. And a sales history that does not record when you had nothing to sell teaches the model that demand was low exactly when it was highest.',
    },
    {
      question: 'How do we know a recommender is adding anything?',
      answer:
        'By holding out a group who see no recommendations, and measuring incremental basket value rather than click-through. Click-through rewards showing people what they were already going to buy. Without the holdout, attribution credits the recommender with sales that would have happened anyway, which is why almost every reported uplift figure is larger than the real one.',
    },
    {
      question: 'Why does personalisation end up recommending bestsellers?',
      answer:
        'Because that is what optimising click-through selects for. Popular items get clicked, the model learns to show them, the metric improves and the recommender ends up doing the job a category page already did. If the output looks like your top-sellers list, the objective is wrong rather than the algorithm.',
    },
    {
      question: 'Where should a retailer start if none of this exists yet?',
      answer:
        'With phantom stock: finding lines the system believes are in stock while sales have stopped dead. It needs no machine learning, only daily sales and stock snapshots on the same clock, and it usually surfaces available sales nobody knew were being lost. It also proves whether anyone will act on a report, which is worth knowing before commissioning a forecasting programme.',
    },
  ],

  image: '/img/ind-retail.svg',
  published: true,
  updated: '2026-08-30',
};


const healthcare: Playbook = {
  slug: 'healthcare',
  industry: 'Healthcare',
  title: 'Data and AI Use Cases in Healthcare Operations',
  description:
    'Six data and AI use cases in hospital and clinic operations — scheduling, capacity, supply, revenue cycle — each with the data it needs, how to prove it worked, and where it fails. Clinical decision support is deliberately out of scope.',
  audience:
    'Written for operations, finance and IT leads at hospitals, clinic groups and diagnostics chains. It covers how a provider runs, not how a clinician decides. It assumes no data science background.',
  standfirst:
    'Six things healthcare providers run on their operational data: no-show prediction, clinic scheduling, inpatient capacity forecasting, theatre utilisation, supply and consumables, and revenue cycle. Nothing here touches diagnosis or treatment — that is a regulated activity with a different evidence bar, and it is not what this document is about.',

  useCases: [
    {
      id: 'no-shows',
      name: 'No-show prediction',
      summary: 'Estimate who will not attend, early enough to do something about it.',
      what:
        'Appointment history, lead time, demographics, distance and prior attendance estimate the probability that a booking will not be kept, so reminders or overbooking can be targeted rather than applied to everyone.',
      needs: [
        'Attendance outcomes recorded consistently, with cancellations distinguished from failures to attend. Where the two are one field, nothing built on it means anything.',
        'Lead time between booking and appointment, which is usually the strongest single predictor.',
        'A reminder or overbooking process that can actually be varied by patient, or the prediction changes nothing.',
      ],
      proof:
        'The no-show rate itself, against a comparable clinic or period. This is the measurement everyone skips: the published work shows no-shows can be predicted, and says much less about whether acting on the prediction reduces them.',
      fails:
        'On overbooking, if the model is trusted too far. A clinic that overbooks on a prediction and is wrong has a waiting room of people who did attend. It also fails on fairness: the features that predict non-attendance — distance, deprivation, prior misses — describe access barriers, and a model that quietly deprioritises those patients has turned a disadvantage into a policy.',
      evidence: FINDINGS.noShowPredictable,
    },
    {
      id: 'clinic-scheduling',
      name: 'Clinic scheduling',
      summary: 'Build a template that matches how long appointments actually take.',
      what:
        'Historical consultation durations by clinician and appointment type set slot lengths and clinic templates, instead of the fifteen minutes everybody gets because that is what the template has always said.',
      needs: [
        'Actual start and end times, not scheduled ones. Most systems record the second and not the first.',
        'Appointment type recorded consistently, and honestly — where "follow-up" absorbs three different kinds of visit, the average is meaningless.',
        'Clinician-level variation acknowledged as legitimate rather than treated as non-compliance.',
      ],
      proof:
        'Clinic overrun, patient waiting time and idle slots, together. Reducing overrun by lengthening every slot is not an improvement, it is fewer patients seen.',
      fails:
        'When the template is optimised centrally and imposed. Clinic staff know which patients need longer, and a schedule that removes their ability to say so gets worked around within a fortnight.',
    },
    {
      id: 'capacity-forecasting',
      name: 'Inpatient capacity forecasting',
      summary: 'Forecast beds needed, far enough ahead to staff for it.',
      what:
        'Admission history, seasonality, day-of-week patterns and expected length of stay project occupancy, so staffing and elective scheduling can be set against the forecast rather than against last week.',
      needs: [
        'Admission, discharge and transfer events with reliable timestamps.',
        'Length of stay by specialty and case mix, which varies enormously and averages badly.',
        'Several years of history to separate seasonality from trend, including whatever unusual period your data contains and a decision about whether to exclude it.',
      ],
      proof:
        'Forecast error at the horizon your staffing decisions are actually made on. A forecast that is accurate a day ahead and useless three weeks ahead does not help anybody rostering.',
      fails:
        'On discharge timing, which is where the real variance lives and which depends on decisions — social care, transport, pharmacy — mostly outside the model. A capacity forecast that assumes discharge behaves predictably is forecasting the wrong thing.',
    },
    {
      id: 'theatre-utilisation',
      name: 'Theatre and equipment utilisation',
      summary: 'Find where expensive capacity is standing idle, and why.',
      what:
        'Session start and finish times, turnaround intervals and cancellation reasons show where theatre or scanner time is lost. Counting and attribution rather than machine learning, and usually the fastest payback here.',
      needs: [
        'Timestamps at each step, not just a session block.',
        'Cancellation reasons from a short enough list that they are chosen honestly.',
        'Case duration by procedure and surgeon, as observed rather than as booked.',
      ],
      proof:
        'Utilisation and cases per list against the current baseline, plus on-the-day cancellations. If utilisation rises while cancellations rise, the lists have simply been overfilled.',
      fails:
        'When the data is entered by the people the numbers will judge, and that conflict is not acknowledged. Turnaround times become uniformly excellent and nothing changes.',
    },
    {
      id: 'supplies',
      name: 'Supplies and consumables',
      summary: 'Hold what a procedure cannot proceed without, and stop holding the rest.',
      what:
        'Consumption by procedure, lead times and expiry set stock levels for consumables and implants. Expiry makes this harder than industrial inventory: overstocking is not merely tied-up cash, it is waste with a date on it.',
      needs: [
        'Consumption linked to procedures rather than to a stores issue.',
        'Real lead times, and shelf life at the point of receipt rather than at manufacture.',
        'A criticality judgement made clinically, not by unit price.',
      ],
      proof:
        'Value held and value expired, against stock-outs that delayed or cancelled a procedure. All three, always.',
      fails:
        'When criticality is inferred from cost. The item that stops a list is often inexpensive, and the costly one on the shelf is frequently the one that expires unused.',
    },
    {
      id: 'revenue-cycle',
      name: 'Revenue cycle and claims',
      summary: 'Find why claims are rejected, before they are submitted.',
      what:
        'Rejection history by payer, procedure and reason identifies the patterns that cause denials — a missing authorisation, a coding mismatch, an eligibility gap — so they can be caught at submission rather than discovered at rejection.',
      needs: [
        'Denial reason codes retained and joined to the original claim.',
        'Payer rules in some structured form, which is usually the largest piece of work.',
        'A resubmission process that records what was changed, or nothing can be learned from a success.',
      ],
      proof:
        'First-pass acceptance rate and days in accounts receivable, against the current baseline. Denials overturned on appeal matter less than denials never incurred.',
      fails:
        'When payer rules change faster than the analysis is refreshed. A model built on last year’s denial patterns confidently prevents last year’s denials.',
    },
  ],

  readiness: [
    {
      name: 'Timestamps describe what happened, not what was booked',
      detail:
        'Scheduling, capacity and theatre analysis all rest on when things actually started and finished. Most systems reliably record the scheduled time and unreliably record the actual one, and no analysis recovers a timestamp nobody captured.',
    },
    {
      name: 'Attendance outcomes distinguish a cancellation from a no-show',
      detail:
        'A patient who rang to cancel and a patient who did not arrive are different events with different causes and different remedies. Where one field holds both, no-show work cannot begin.',
    },
    {
      name: 'A named owner for every action the output triggers',
      detail:
        'A no-show score changes who gets a reminder call; a capacity forecast changes a roster; a denial prediction changes what is checked before submission. Where no role owns that action today, the output has nowhere to go.',
    },
    {
      name: 'Somebody is accountable for the fairness of each model',
      detail:
        'Operational models in healthcare allocate access — who is reminded, who is overbooked, whose appointment is shortened. The features that predict non-attendance largely describe barriers to attending, so a model optimised for utilisation can quietly disadvantage exactly the patients who most need the appointment. That review is a standing responsibility, not a launch checklist item.',
    },
  ],

  faq: [
    {
      question: 'Can patient no-shows actually be predicted?',
      answer:
        'Yes, with an important caveat about what that buys you. A study across two Brazilian hospital datasets — 8,371 CT appointments with a 6.65% no-show rate and 7,413 consultations with 19.03% — reached sensitivity above 0.94 with the better combinations of model and resampling. The authors also state plainly that the results are case-specific and not generalisable between settings, and that class imbalance badly affects every metric except sensitivity. Prediction is the easy half; the published work says much less about whether acting on the predictions reduces the no-show rate, which is the only thing that matters to a clinic.',
    },
    {
      question: 'Why does this playbook not cover clinical AI?',
      answer:
        'Because diagnosis and treatment support are regulated activities with a different evidence bar — prospective validation, regulatory clearance, clinical governance — and a page about operations is the wrong place for them. Everything here concerns how a provider runs: who is expected, how long a list takes, what is in the store, why a claim was denied. That work is valuable, unglamorous, and needs no clinical claim to justify itself.',
    },
    {
      question: 'What is the fairness risk in operational healthcare models?',
      answer:
        'That they allocate access while appearing to allocate resources. The features that predict non-attendance — distance, prior misses, deprivation — mostly describe barriers to attending. A model that deprioritises those patients has converted a disadvantage into a policy, and it will show up as an efficiency gain on every dashboard you have. Someone has to be accountable for reviewing that, continuously.',
    },
    {
      question: 'Which of these pays back fastest?',
      answer:
        'Usually theatre and equipment utilisation, or the phantom capacity that scheduling analysis uncovers. Both are counting exercises rather than machine learning, both are measurable within a quarter, and both tend to find that the losses are not where everyone assumed.',
    },
    {
      question: 'Where should a provider start if none of this exists yet?',
      answer:
        'By checking whether actual start and finish times are captured, and whether cancellations and no-shows are distinguishable. Neither needs any analysis at all, both are prerequisites for most of this list, and discovering that they are missing is worth more than a prediction model built on the gap.',
    },
  ],

  image: '/img/ind-healthcare.svg',
  /*
   * Held back deliberately, not abandoned. The content below is complete and
   * checked; publishing it is a one-word change.
   *
   * Everything else here describes how a business runs. This one touches how a
   * provider treats people — who gets reminded, who gets overbooked, whose
   * appointment is shortened — and that deserves a closer read before it goes
   * out under the firm's name than the other five did.
   */
  published: false,
  updated: '2026-08-30',
};

/**
 * Industries with a playbook announced but not written.
 *
 * Empty, because all six are published. The mechanism stays: a seventh industry
 * gets listed here and appears on the index as in preparation rather than as a
 * thin page, which would compete with the real ones and earn nothing.
 */
type PlannedPlaybook = { slug: string; industry: string; image: string };

/* Typed explicitly rather than inferred. `[] as const` gives an empty array the
   element type `never`, so the index page's .map() over it stops compiling the
   moment the last industry is published — which is exactly when nobody is
   looking at this file. */
const PLANNED: PlannedPlaybook[] = [
  { slug: 'healthcare', industry: 'Healthcare', image: '/img/ind-healthcare.svg' },
];

export const PLAYBOOKS: Playbook[] = [manufacturing, oilAndGas, logistics, fintech, retail, healthcare];

export const PLANNED_PLAYBOOKS = PLANNED;

export const getPlaybook = (slug: string): Playbook | undefined =>
  PLAYBOOKS.find((p) => p.slug === slug && p.published);

export const publishedPlaybooks = (): Playbook[] => PLAYBOOKS.filter((p) => p.published);
