import { FINDINGS, type Finding } from '@/lib/playbooks/sources';

/**
 * The Data & AI Use Case Playbooks.
 *
 * Content as data rather than JSX, for two reasons. The page and the printable
 * one-pager render the same object, so the document a reader files cannot
 * disagree with the page they read it from — the same rule the calculator's
 * summary sheet follows. And a playbook that is data can be checked
 * mechanically: tools/check-playbooks.mjs walks these objects and fails if a
 * figure appears without a source attached to it.
 *
 * Written for the person who has been asked "what should we be doing with AI"
 * and has to come back with something defensible. That reader is not short of
 * lists of use cases; they are short of a way to tell which ones are real, what
 * each actually requires, and how they would know if it worked. So every use
 * case here carries what it needs and where it fails, and the failure modes are
 * not softened — a playbook that never says "don't" is a brochure.
 */

export type UseCase = {
  id: string;
  name: string;
  /** One line, for scanning. */
  summary: string;
  /** What it does, in terms an operations lead would use. */
  what: string;
  /** The data it needs before it can work at all. The usual reason projects stall. */
  needs: string[];
  /** How you would know it worked — stated before you start, not after. */
  proof: string;
  /** Where it goes wrong. Written plainly, because this is the useful part. */
  fails: string;
  /** Evidence backing the maturity claim, where any exists. */
  evidence?: Finding;
};

export type Playbook = {
  slug: string;
  industry: string;
  /**
   * The page's H1, and its title in a search result. Kept under 62 characters
   * so it is not truncated there.
   *
   * "Data and AI" rather than "AI", because two of the six use cases involve no
   * machine learning whatever and calling the set AI would be the same
   * overselling this document exists to argue against. It costs nothing in
   * search: "Data and AI Use Cases in Manufacturing" contains the phrase
   * people actually type, word for word.
   */
  title: string;
  /** Meta description and the listing card's blurb. */
  description: string;
  /** Who this is for, and who it is not for. */
  audience: string;
  /**
   * The opening paragraph, under the H1.
   *
   * Names the use cases outright rather than describing the document. Somebody
   * arriving on "AI use cases in manufacturing" wants to see the list in the
   * first sentence, and an assistant summarising the page quotes what is
   * nearest the heading.
   */
  standfirst: string;
  useCases: UseCase[];
  /** What has to be true before any of the above is worth starting. */
  readiness: { name: string; detail: string }[];
  /** Question-shaped, because these are the questions people actually type. */
  faq: { question: string; answer: string }[];
  /**
   * The industry motif from public/img, generated by tools/gen-art.mjs.
   *
   * Line art rather than a photograph, and the same grammar across all six: the
   * shape is the ordinary case, the accent mark is the exception the data is
   * for — a bottleneck on a line, a route running long, a spike in a trace. A
   * stock photograph of a factory would say only "factory".
   */
  image: string;
  published: boolean;
  updated: string;
};

const manufacturing: Playbook = {
  slug: 'manufacturing',
  industry: 'Manufacturing',
  title: 'Data and AI Use Cases in Manufacturing',
  description:
    'Six data and AI use cases in manufacturing, each with the data it requires, how to prove it worked, and where it fails. Every figure sourced, including the ones everyone quotes without checking.',
  audience:
    'Written for plant, operations and IT leads at manufacturers who have been asked what they should be doing with AI and need an answer they can defend. It assumes no data science background and no existing platform.',
  standfirst:
    'Six things manufacturers actually run on their data: predictive maintenance, automated visual inspection, demand forecasting, OEE analysis and scheduling, energy optimisation, and spares and inventory. Two of the six involve no machine learning at all. For each one this sets out the data it needs before it can work, how you would prove it worked, and the conditions under which it fails.',

  useCases: [
    {
      id: 'predictive-maintenance',
      name: 'Predictive maintenance',
      summary: 'Predict a failure from sensor data early enough to schedule the repair.',
      what:
        'Equipment sensor readings — vibration, temperature, current draw, acoustic signature — are monitored for the pattern that precedes a particular failure, so the machine is taken down deliberately rather than unexpectedly. The value is not fewer repairs; it is the same repairs, at a time you chose.',
      needs: [
        'Sensor data at an interval fine enough to see the failure develop. Hourly averages hide most bearing faults.',
        'A maintenance history that records what actually failed, not just that an engineer attended. This is the one that is usually missing.',
        'Enough past failures of the same kind to learn from. A machine that has failed twice in five years cannot support a model, whatever a vendor says.',
        'Somebody whose job it is to act on an alert. An unactioned prediction is a cost, not a saving.',
      ],
      proof:
        'Agree before you start: which asset, which failure mode, and what the current rate of unplanned stoppages on it is. Then measure the same number six months later. If nobody can state the current rate, that is the first project, not this one.',
      fails:
        'Most often for want of labelled failures, not for want of a model. It also fails quietly when the model is scored on accuracy. Worked example: suppose a machine fails on two days in a hundred — a model that always predicts "fine" is then right ninety-eight times out of a hundred, and is completely useless. Insist on being shown how often it caught real failures and how often it cried wolf, as two separate numbers.',
      evidence: FINDINGS.deploymentGap,
    },
    {
      id: 'visual-inspection',
      name: 'Automated visual inspection',
      summary: 'A camera and a model catch surface defects at line speed.',
      what:
        'Images of parts are classified as acceptable or not, on the line, at production rate. It suits defects that are genuinely visible and consistently defined: surface finish, print and label errors, missing components, weld appearance.',
      needs: [
        'Consistent lighting and camera position. This is more of the work than the model is, and skimping on it is the usual reason a pilot that worked stops working.',
        'Labelled example images of each defect type, including borderline ones.',
        'An agreed definition of a defect. Where two inspectors disagree, a model will disagree too, and you will blame the model.',
        'A decision about what happens to a rejected part, before go-live.',
      ],
      proof:
        'Run it alongside your existing inspection for a period, on the same parts, and compare. Count both the defects it missed and the good parts it rejected — the second is what quietly costs you money after go-live.',
      fails:
        'When the defect is not reliably visible in the image, when the product changes more often than the model is retrained, and when the true defect rate is so low that the training set contains almost no examples of what you are looking for.',
    },
    {
      id: 'demand-forecasting',
      name: 'Demand forecasting',
      summary: 'Forecast what will be ordered, to plan production and stock against it.',
      what:
        'Historical orders, seasonality and known external drivers are used to project demand by SKU and period. The output is only useful if it changes a decision — how much to make, what to hold, when to buy.',
      needs: [
        'Several years of order history at the granularity you plan at.',
        'A record of stock-outs. Sales history alone systematically understates demand you could not meet.',
        'Knowledge of promotions and one-off events, or the model will learn them as seasonality.',
      ],
      proof:
        'Compare against what you do now, which is usually last period plus a judgement. Measure forecast error on the same SKUs over the same window. A model that cannot beat "same as last month" is not ready, and finding that out early is a good outcome.',
      fails:
        'On short histories, on products with few large customers where one phone call outweighs any pattern, and after a genuine change in the market — a model trained on the past is confidently wrong about a step change.',
    },
    {
      id: 'oee-scheduling',
      name: 'OEE analysis and scheduling',
      summary: 'Find where output is actually lost, then schedule around it.',
      what:
        'Machine states, changeovers and stoppage reasons are combined into a picture of where availability, performance and quality are lost. Frequently the most valuable finding is that the losses are not where everyone assumed.',
      needs: [
        'Machine state capture that does not rely on someone filling in a sheet.',
        'A stoppage reason code list short enough to be used honestly. Forty codes become "other".',
        'Changeover times as they are, not as the standard says.',
      ],
      proof:
        'This one earns its place before any model does: if the loss analysis surprises the people who run the line, it has already paid for itself, and if it confirms what they knew, you have saved yourself the next project.',
      fails:
        'When the data is entered by the people being measured by it, without that conflict being acknowledged and designed around.',
    },
    {
      id: 'energy',
      name: 'Energy and utilities optimisation',
      summary: 'Match consumption to production, and find what draws power for nothing.',
      what:
        'Meter data is set against production output to find plant drawing power out of proportion to what it makes — compressed air leaks, chillers running against ambient conditions, equipment idling through breaks.',
      needs: [
        'Sub-metering. A single site meter tells you the total and nothing else.',
        'Production output on the same clock as the meter readings.',
        'Tariff structure, including any demand or peak charges, which often dominate the bill.',
      ],
      proof:
        'kWh per unit produced, before and after, on comparable production. Normalise for output or you will report a saving that is just a quiet month.',
      fails:
        'Rarely on the analysis and often on the follow-through: the finding is a maintenance job nobody is assigned, and twelve months later the leak is still there.',
    },
    {
      id: 'spares',
      name: 'Spares and inventory optimisation',
      summary: 'Hold the parts that would stop the line, and stop holding the rest.',
      what:
        'Consumption history, lead times and the consequence of a stock-out are used to set holdings per part. Cash is usually released rather than spent.',
      needs: [
        'Accurate lead times, which are frequently recorded as the supplier’s quote rather than reality.',
        'A criticality judgement per part — what actually stops if this is missing.',
        'Issue history from stores, at part level.',
      ],
      proof:
        'Value held against stock-outs causing downtime. Both, always: cutting inventory while causing one line stoppage is not a saving, and reporting only the first is how these projects get a bad name.',
      fails:
        'When criticality is inferred from price. The part that stops the plant is often cheap, and the expensive one on the shelf is often the one that never fails.',
    },
  ],

  readiness: [
    {
      name: 'You can say what a number means, and get the same answer twice',
      detail:
        'If two departments produce different output figures for the same week, that is the project. Every use case above inherits the definitions underneath it, and no model repairs a disagreement about what "produced" means.',
    },
    {
      name: 'The data leaves the machine that made it',
      detail:
        'Readings trapped in a PLC, an HMI or a local historian nobody can query are not available to anything. Getting them out reliably is unglamorous and is usually the longest task in the plan.',
    },
    {
      name: 'History exists, and goes back far enough',
      detail:
        'Models learn from what has happened. Six weeks of data supports nothing seasonal and no rare event, and no technique compensates for history that was never kept.',
    },
    {
      name: 'Somebody owns the decision the output feeds',
      detail:
        'Every use case above ends in a decision — take the machine down, reject the part, order the stock. Where no named person makes that decision today, the output has nowhere to go, and this is the most common reason a technically successful pilot is quietly abandoned.',
    },
  ],

  faq: [
    {
      question: 'How much does unplanned downtime actually cost a manufacturer?',
      answer:
        'The most quoted figure is about $1.4 trillion a year across the world’s 500 largest companies, roughly 11% of revenue, from Senseye and Siemens. It is worth knowing how that was arrived at before quoting it: 181 online interviews gathered over four years, combined with the publisher’s own product data, and the Global 500 total is extrapolated from public information rather than surveyed. The report itself calls its combined figures indicative only. It is a reasonable order of magnitude and a poor substitute for your own number, which you can get from your stoppage log and your contribution per hour.',
    },
    {
      question: 'Does AI predictive maintenance actually work, or is it a pilot that never ships?',
      answer:
        'Both, depending on the case. A 2025 review in Applied Sciences classified 60 published studies by how far they got: 40 reached live deployment with alerts feeding real work orders, 4 were validated retrospectively against plant data, and 16 never left benchmarks or simulation. So it demonstrably ships — and a third of the published work has not been tested against a real plant. Ask any vendor which of those three their evidence is.',
    },
    {
      question: 'What is the most common reason these projects fail?',
      answer:
        'Not the model. The recurring barrier in the published work is data: labelled failure examples are expensive and slow to gather, and industrial data is heterogeneous and heavily imbalanced. In practice the projects that stall are the ones where the maintenance history records that somebody attended, but not what failed.',
    },
    {
      question: 'Why should I distrust a high accuracy score on a failure-prediction model?',
      answer:
        'Because on a machine that fails on 2% of days, always predicting "no failure" is 98% accurate. Reviews of this literature note that high accuracy is frequently reported without disclosing how many faulty examples were in the data. Ask instead how many real failures it caught and how many false alarms it raised, as two separate numbers.',
    },
    {
      question: 'Where should a manufacturer start if none of this exists yet?',
      answer:
        'With the loss analysis, not with a model. Work out where output is actually lost and whether everyone agrees on the numbers. It is cheap, it needs no machine learning, and it tells you which of the use cases above is worth anything to you — which is a different answer at every plant.',
    },
  ],

  image: '/img/ind-manufacturing.svg',
  published: true,
  updated: '2026-08-30',
};


const oilAndGas: Playbook = {
  slug: 'oil-and-gas',
  industry: 'Oil & Gas',
  title: 'Data and AI Use Cases in Oil & Gas',
  description:
    'Six data and AI use cases in oil and gas, each with the data it needs, how to prove it worked, and where it fails. Sourced, including a published account of what a real offshore programme actually took.',
  audience:
    'Written for operations, integrity and digital leads at operators and service companies who need to separate what is running in production from what is running in a conference slide. It assumes no data science background.',
  standfirst:
    'Six things operators actually run on their data: rotating equipment monitoring, corrosion and integrity, production optimisation, flaring and emissions, drilling and completion analysis, and inventory for critical spares. For each one this sets out the data it needs, how you would prove it worked, and where it fails.',

  useCases: [
    {
      id: 'rotating-equipment',
      name: 'Rotating equipment monitoring',
      summary: 'Catch a turbine, compressor or pump degrading before it trips.',
      what:
        'Vibration, temperature, pressure and flow are watched for the signature that precedes a failure on a specific machine. On a platform the value is not the repair cost — it is avoiding an unplanned shutdown of production, and avoiding a helicopter mobilisation to fix something that could have been done on the next scheduled visit.',
      needs: [
        'A historian that actually holds the tags at the resolution the fault needs, and that somebody can query without raising a ticket.',
        'CMMS work orders that record what was found and what was replaced. The published offshore programme below hit exactly this: not all maintenance had gone through the work-order system.',
        'Somebody onshore who owns the alert and can get it into the next offshore work pack.',
        'Equipment engineers involved from the start. A modelling partner without domain knowledge slows the work rather than speeding it.',
      ],
      proof:
        'Pick the assets and the failure modes first, and write down the current rate of unplanned trips on them. Six months later, count again. Also count alerts that led to an intervention against alerts that were dismissed — a model nobody acts on is a subscription, not a system.',
      fails:
        'It stalls on data availability far more often than on modelling, and the delay is measured in months not weeks. It also fails when the alert says only that something is abnormal: a "check engine" light on a compressor tells an offshore team nothing they can act on, and they stop opening them.',
      evidence: FINDINGS.offshoreDataFirst,
    },
    {
      id: 'corrosion-integrity',
      name: 'Corrosion and asset integrity',
      summary: 'Target inspection at the parts of the system most likely to be thinning.',
      what:
        'Inspection history, process conditions, fluid composition and material data are combined to rank circuits by likely degradation, so inspection effort goes where the risk is rather than where the schedule says.',
      needs: [
        'Inspection results in a queryable form, not as scanned PDFs of reports.',
        'Consistent circuit and location identifiers across the systems. This is usually the hard part: the same line has three identifiers in three systems.',
        'Process history for the same period as the inspection findings.',
      ],
      proof:
        'Compare the ranking against what the next inspection campaign actually finds. It is a good sign when the model puts thinning at the top of the list before anyone has looked, and an honest failure when it does not.',
      fails:
        'Where inspection coverage has been driven by accessibility rather than risk, the history is biased towards what was easy to reach — and a model trained on it inherits that blind spot precisely where you most need it not to.',
    },
    {
      id: 'production-optimisation',
      name: 'Production optimisation',
      summary: 'Find where wells and facilities are running below what conditions allow.',
      what:
        'Well tests, choke settings, pressures and facility constraints are used to find the gap between what a well is producing and what it could produce, and to say which constraint is binding.',
      needs: [
        'Well test data at a usable frequency, and honesty about how old each test is.',
        'Facility constraints written down somewhere other than in an operator’s head.',
        'Allocation that reconciles, or the model will optimise against a number that is already wrong.',
      ],
      proof:
        'Against the current process, on the same wells, over a period long enough to cover normal variation. Uplift claimed against a best-ever month is not uplift.',
      fails:
        'When allocation is contested. If two departments disagree about what a well produced last month, no optimisation of that figure will be believed, and the argument is the project.',
    },
    {
      id: 'flaring-emissions',
      name: 'Flaring and emissions monitoring',
      summary: 'Account for what is flared and vented, and find the recurring causes.',
      what:
        'Flare meter data, process events and equipment status are brought together to attribute flaring to causes — a compressor trip, a start-up, a specific plant upset — rather than reporting a monthly total nobody can act on.',
      needs: [
        'Flare metering that is calibrated, and known gaps where it is not.',
        'Event and alarm history on the same clock as the flare data.',
        'An agreed reporting basis, because the regulatory figure and the engineering figure are rarely the same number.',
      ],
      proof:
        'Volume attributed to an identified cause, as a share of the total. Going from "we flared this much" to "this much of it came from these four causes" is the whole value, and it is measurable.',
      fails:
        'When metering is poor and the analysis quietly becomes an estimate presented with the confidence of a measurement — which is a problem if the number ends up in a regulatory return.',
    },
    {
      id: 'drilling-analysis',
      name: 'Drilling and completion analysis',
      summary: 'Compare wells honestly enough to learn something from the last one.',
      what:
        'Daily reports, mud logs, bit records and time breakdowns are normalised so that wells can be compared — where non-productive time went, which parameter choices went with better runs.',
      needs: [
        'Daily drilling reports in a structured form. They are usually free text, and turning them into data is most of the work.',
        'A consistent operations coding scheme across rigs and contractors.',
        'Enough wells in comparable formations to draw any conclusion at all.',
      ],
      proof:
        'Non-productive time per well section against the historical baseline for the same formation. Comparing against a different field is not a comparison.',
      fails:
        'On small samples. A dozen wells across three basins supports anecdote, not inference, and dressing that up as a model gives the anecdote unearned authority.',
    },
    {
      id: 'critical-spares',
      name: 'Critical spares and inventory',
      summary: 'Hold what a shutdown would turn on, and stop holding the rest.',
      what:
        'Consumption, lead time and the cost of a stock-out set holdings for each part. In this sector the asymmetry is severe: an inexpensive seal can hold up production worth far more than the whole store.',
      needs: [
        'Real lead times, which for long-lead items are frequently recorded as the original quote rather than as delivered.',
        'A criticality judgement per part, made by engineers rather than inferred from price.',
        'Issue history at part level, including what was cannibalised from another unit.',
      ],
      proof:
        'Value held against stock-outs that caused deferment. Report both or the exercise becomes a cost-cutting number with a production loss hidden behind it.',
      fails:
        'When criticality is inferred from cost. The part that stops the platform is often cheap, and the expensive one on the shelf is often the one that never fails.',
    },
  ],

  readiness: [
    {
      name: 'The historian is reachable, and the tags mean what they say',
      detail:
        'Every use case here starts with time-series data somebody can query. Where the tag list is undocumented and half the names are inherited from a previous operator, that is the first piece of work and it is not a modelling task.',
    },
    {
      name: 'Maintenance history records what failed, not just that somebody attended',
      detail:
        'This is the single most common gap, and it is documented in the offshore programme cited above: maintenance that never went through the work-order system leaves no history to learn from. It cannot be reconstructed later.',
    },
    {
      name: 'One identifier per physical thing, across systems',
      detail:
        'A line, a vessel or a pump usually carries different identifiers in the historian, the CMMS and the inspection database. Until they can be joined, every one of these use cases is a manual reconciliation exercise wearing a model.',
    },
    {
      name: 'An onshore owner for every alert',
      detail:
        'Offshore crews are busy and an alert without a named owner onshore is an alert that gets acknowledged and forgotten. This is a rota question, not a technology one, and it decides whether any of this survives its first six months.',
    },
  ],

  faq: [
    {
      question: 'How long does an offshore predictive maintenance programme take to produce anything?',
      answer:
        'Longer than the pilot timeline usually says. In a published account of a 24-month programme across deepwater Gulf of Mexico platforms, the first predictive model went live six months after kickoff, and the operator attributed the delay to a lack of the required data rather than to modelling difficulty. Forty-six models were eventually running in production. Plan for the data work to be the schedule.',
    },
    {
      question: 'What is the most common data problem in oil and gas AI projects?',
      answer:
        'Maintenance history that records an intervention but not a failure mode. The offshore programme cited here found that not all maintenance had been raised through the work-order system, so the record of what actually failed was incomplete. Sensor data is usually abundant; the labels that make it useful are usually not.',
    },
    {
      question: 'Why do offshore crews stop acting on model alerts?',
      answer:
        'Because early alerts tend to behave like a check-engine light — they say something is abnormal without saying what or what to do. The published programme describes exactly this and had to retrain models to reduce false positives. An alert that cannot be turned into a work-pack line is an alert that gets dismissed, and once dismissal becomes habit the system is finished regardless of its accuracy.',
    },
    {
      question: 'Do we need a data scientist or an equipment engineer?',
      answer:
        'Both, and the second is the one usually missing. The offshore programme reported that its service partner lacked sufficient expertise in oil and gas equipment, which hampered the work. A model that does not know a glycol system from a gas compressor produces alerts that a rotating equipment engineer can see are nonsense.',
    },
    {
      question: 'Where should an operator start if none of this exists yet?',
      answer:
        'With whether the historian and the CMMS can be joined on a common identifier for the same physical asset. It needs no machine learning, it is the prerequisite for every use case above, and finding out that it cannot be done is worth knowing before a modelling contract is signed rather than after.',
    },
  ],

  image: '/img/ind-energy.svg',
  published: true,
  updated: '2026-08-30',
};


const logistics: Playbook = {
  slug: 'logistics',
  industry: 'Logistics',
  title: 'Data and AI Use Cases in Logistics',
  description:
    'Six data and AI use cases in logistics and distribution, each with the data it needs, how to prove it worked, and where it fails. Every figure sourced, with what the published forecasting evidence does and does not support.',
  audience:
    'Written for operations, network and IT leads at carriers, 3PLs and distributors who need to know which of these is worth starting and what each one will demand of their data first. It assumes no data science background.',
  standfirst:
    'Six things logistics operations actually run on their data: demand and volume forecasting, route and load planning, warehouse slotting, ETA prediction, fleet maintenance, and freight cost and invoice audit. Two of the six need no machine learning. For each one this sets out the data it needs, how you would prove it worked, and where it fails.',

  useCases: [
    {
      id: 'volume-forecasting',
      name: 'Demand and volume forecasting',
      summary: 'Forecast what will need moving, to staff and book capacity against it.',
      what:
        'Order and shipment history, seasonality and known drivers project volume by lane, site and period. The output only matters if it changes something you commit to in advance — shifts rostered, vehicles booked, space taken.',
      needs: [
        'Several years of history at the granularity you actually plan at. A network total does not help a site manager staff a shift.',
        'A record of what you turned away or could not move, or the history understates demand exactly where it was tightest.',
        'Promotions, contract wins and losses marked, or the model learns a one-off customer as a season.',
      ],
      proof:
        'Against your current method, which is usually last period plus judgement, on the same lanes over the same window. The published reviews report machine learning beating classical baselines by meaningful margins, but those are the authors’ datasets and not a promise about yours — your own baseline is the only comparison that decides anything.',
      fails:
        'On lanes dominated by a handful of customers, where one contract decision outweighs any pattern in the history. It also fails after a genuine step change in the network, because a model trained on the old shape is confident and wrong.',
      evidence: FINDINGS.forecastGains,
    },
    {
      id: 'route-load-planning',
      name: 'Route and load planning',
      summary: 'Build drops and loads that respect what the vehicle and the driver can actually do.',
      what:
        'Orders, vehicle capacities, time windows and driver hours are solved into routes. This is optimisation rather than learning, and it is one of the two here that involves no machine learning at all.',
      needs: [
        'Accurate service times per drop. Planned times that everyone knows are wrong produce routes nobody runs.',
        'Real vehicle constraints, including the ones drivers work around informally.',
        'Access restrictions and delivery windows as they are enforced, not as the customer master says.',
      ],
      proof:
        'Planned versus actual, per route, over a month: how many drops moved, how much time was added, how often a driver rebuilt the run themselves. A plan the depot quietly overrides has failed however good the objective function looks.',
      fails:
        'When the model’s picture of a drop is a customer record and the driver’s is a loading bay with a locked gate at four o’clock. The gap between those two is where these projects die.',
    },
    {
      id: 'warehouse-slotting',
      name: 'Warehouse slotting',
      summary: 'Put fast-moving stock where it costs least to pick.',
      what:
        'Pick history, product dimensions and affinity between items decide where each SKU sits, cutting travel per pick. Also not machine learning — it is counting and arithmetic, and it usually pays back faster than anything else on this list.',
      needs: [
        'Pick-level history with location and timestamp, not order-level summaries.',
        'Accurate product dimensions and weights, which are very often wrong in the master data.',
        'A window in which to physically move stock, which is an operational cost people forget to budget.',
      ],
      proof:
        'Travel distance or picks per hour, measured before and after on comparable volume. Normalise for volume or a quiet month will look like an improvement.',
      fails:
        'When the analysis is run once and never again. Slotting decays as the range changes, and a layout optimised for last spring is worse than one nobody optimised.',
    },
    {
      id: 'eta-prediction',
      name: 'ETA prediction',
      summary: 'Tell a customer when it will arrive, and be right often enough to be believed.',
      what:
        'Telematics, historical transit times, traffic and dwell patterns predict arrival windows for a consignment in flight.',
      needs: [
        'Position data at a frequency that captures dwell, not just departure and arrival.',
        'Historical actuals per lane, including the bad days rather than a cleaned set.',
        'A defined event for "arrived", because gate-in, unload and POD are three different times and pretending otherwise makes the whole measurement incoherent.',
      ],
      proof:
        'The share of deliveries landing inside the promised window, and the size of the misses when they fall outside. Publishing a narrow window you hit half the time is worse than a wide window you hit reliably.',
      fails:
        'At the last leg and in yards, where the variance actually lives. A model that nails line-haul and cannot predict a three-hour wait for a door is a model that gets the customer promise wrong.',
    },
    {
      id: 'fleet-maintenance',
      name: 'Fleet maintenance',
      summary: 'Take the vehicle off the road on your schedule, not on the hard shoulder.',
      what:
        'Telematics fault codes, service history and duty cycle are used to schedule work before a breakdown. The value is a planned VOR instead of a recovery and a failed delivery.',
      needs: [
        'Fault codes retained rather than cleared at service, which many workshops do by default.',
        'Service history joined to the vehicle across its whole life, including under a previous operator.',
        'Duty cycle, since the same vehicle on urban multi-drop and on trunking degrades differently.',
      ],
      proof:
        'Roadside breakdowns per vehicle per year, against the same period before. Count planned VOR hours too — trading a breakdown for excessive precautionary downtime is not a win.',
      fails:
        'On mixed fleets with too few of any one model to learn from, and where the maintenance record lives with a contracted workshop who has no reason to give you the detail.',
    },
    {
      id: 'freight-audit',
      name: 'Freight cost and invoice audit',
      summary: 'Check what you were charged against what was agreed and what moved.',
      what:
        'Carrier invoices are reconciled against rate cards, actual weights and dimensions, and the shipment record. Overcharges are usually not fraud — they are re-weighs, accessorials and surcharges that nobody has capacity to check line by line.',
      needs: [
        'Rate cards in a structured form. They frequently arrive as PDFs and turning them into data is the project.',
        'Dimensional data captured at despatch, or you cannot dispute a re-weigh.',
        'A shipment record that can be matched to an invoice line, which sounds trivial and rarely is.',
      ],
      proof:
        'Recovered or avoided spend as a share of freight cost, and the share of invoice lines checked. The second matters: auditing a small sample and extrapolating from it is an estimate, not a finding.',
      fails:
        'When the dispute process costs more than the recovery. Finding an error you will never claim back is an expensive way to feel informed.',
    },
  ],

  readiness: [
    {
      name: 'One identifier follows a consignment end to end',
      detail:
        'Order, shipment, consignment and invoice usually carry different references in different systems. Until they join, every use case here starts with a reconciliation exercise, and most of the effort goes there rather than into the analysis.',
    },
    {
      name: 'Events are timestamped consistently, and "arrived" is defined',
      detail:
        'Gate-in, unload start and POD are three different moments. Where sites record them differently, transit and dwell figures are not comparable between them, and any model built on the mixture inherits the inconsistency.',
    },
    {
      name: 'Master data reflects reality, not the contract',
      detail:
        'Service times, dimensions, access restrictions and delivery windows are frequently what was agreed years ago rather than what happens now. Planning against them produces plans the depot overrides, which is the most common way these projects quietly stop being used.',
    },
    {
      name: 'Somebody owns the decision each output feeds',
      detail:
        'A forecast changes a staffing commitment; a route plan changes what a driver is handed; an audit finding changes a claim. Where no named person makes that call today, the output has nowhere to go, and a technically successful pilot gets abandoned anyway.',
    },
  ],

  faq: [
    {
      question: 'Does machine learning actually forecast logistics demand better than traditional methods?',
      answer:
        'The published evidence says yes, with caveats worth knowing. A 2024 critical review of 119 studies found machine-learning forecasters reporting error reductions of roughly 15–20% against ARIMA, with hybrid models reporting further gains. Those figures are what each set of authors measured on their own data, not a promise about your lanes, and the same review names unreliable input data — missing history, or bias in what was recorded — as a limit that no choice of model removes. Your own current method is the only baseline that decides anything.',
    },
    {
      question: 'Which logistics use case pays back fastest?',
      answer:
        'Usually warehouse slotting or freight invoice audit, and neither involves machine learning. Slotting is counting pick history and moving stock; audit is reconciling invoices against rate cards. Both are unglamorous, both are measurable within a quarter, and both are frequently skipped in favour of something with a better name.',
    },
    {
      question: 'Why do route optimisation projects get rejected by depots?',
      answer:
        'Because the model plans against master data and the driver runs against reality — service times that are optimistic, a delivery window the customer enforces differently, a gate locked at four. When the plan and the ground disagree, the depot rebuilds the run by hand and the system becomes something to work around. The fix is fixing the master data, which is slower and less interesting than the optimisation.',
    },
    {
      question: 'What data do we need before ETA prediction is worth attempting?',
      answer:
        'Position data frequent enough to show dwell rather than just departure and arrival, historical actuals per lane including the bad days, and an agreed definition of "arrived". That last one decides everything downstream: gate-in, unload and POD are three different times, and a model trained on a mixture of them cannot be accurate about any of them.',
    },
    {
      question: 'Where should a logistics operation start if none of this exists yet?',
      answer:
        'By checking whether a consignment can be traced end to end on one identifier, and whether every site means the same thing by "arrived". Neither needs machine learning, both are prerequisites for most of the list above, and discovering that they do not hold is worth more than a forecasting pilot built on top of the gap.',
    },
  ],

  image: '/img/ind-logistics.svg',
  published: true,
  updated: '2026-08-30',
};

/**
 * The rest, declared but not published.
 *
 * They appear on the index as in preparation rather than as pages, because a
 * thin page is worse for this section than no page: it competes with the real
 * one, gives a first-time visitor a bad impression of the set, and earns no
 * links. They get built to the same standard or they do not go up.
 */
const PLANNED = [
  { slug: 'fintech', industry: 'Fintech', image: '/img/ind-financial.svg' },
  { slug: 'retail-ecommerce', industry: 'Retail & E-commerce', image: '/img/ind-retail.svg' },
  { slug: 'healthcare', industry: 'Healthcare', image: '/img/ind-healthcare.svg' },
] as const;

export const PLAYBOOKS: Playbook[] = [manufacturing, oilAndGas, logistics];

export const PLANNED_PLAYBOOKS = PLANNED;

export const getPlaybook = (slug: string): Playbook | undefined =>
  PLAYBOOKS.find((p) => p.slug === slug && p.published);

export const publishedPlaybooks = (): Playbook[] => PLAYBOOKS.filter((p) => p.published);
